### ISSUE TITLE
Initial error when trying blink

### ISSUE THREAD

**Issue by cymplecy** [MrYsLab/telemetrix-rpi-pico#1]
![image](https://user-images.githubusercontent.com/2357428/108892687-12134200-7608-11eb-9205-a4aea7a88e3e.png)
I'd previously downloaded the UTF - done the bootsel - dragged file across and then tried running blink

**Comment by MrYsLab** [comment]
That's not good. I found some issues in autodiscovery if there is another active com port besides the Pico's port.
I made some changes and I uploaded them to pypi.
Could you please try doing a pip install telemetrix-rpi-pico --upgrade and then try again. If you are still seeing a similar issue, please edit the blnk.py file and change:
```
board = telemetrix_rpi_pico.TelemetrixRpiPico()

```
to
```
board = telemetrix_rpi_pico.TelemetrixRpiPico(com_port='com7')
```

I am assuming that com7 is the com port for your pico. If not, then change to the correct com port in the line above.
Please let me know if any of this works. Thanks.

```

**Comment by cymplecy** [comment]
Froze the first time I tried it - just stuck opening or scanning (can't remember words) port

So I yanked the cable and had to force close the window using X at top right

Worked perfectly 2nd attempt but now using COM8 - not at unusual occurrence when windows gets upset about a com port :)
![image](https://user-images.githubusercontent.com/2357428/108908661-7b508080-761b-11eb-8049-d9ec586c279c.png)

**Comment by MrYsLab** [comment]
Great. So I am going to close this if that's ok. Thanks for your help and the report.
