### ISSUE TITLE
Version number confusion

### ISSUE THREAD

**Issue by cymplecy** [MrYsLab/telemetrix-rpi-pico#2]
Hi Alan
I decided to update my install (downloaded uf2 -transferred to pico and pip installed latest) following your tweet about v0.4 being released

I see version numbers but none of them are 0.4 :)

![image](https://user-images.githubusercontent.com/2357428/109801033-d97df480-7c15-11eb-8803-f9da865c7405.png)

**Comment by MrYsLab** [comment]
Hi Simon,
When you installed from pypi, did you type?
```
pip install telemetrix-rpi-pico --upgrade
```
If not, leave out the "upgrade", pip sees that a version is already installed and goes along its merry way and does not install the latest, but gives a cryptic warning. Here is an example:

![Screenshot from 2021-03-03 08-47-59](https://user-images.githubusercontent.com/5189838/109815173-5a7cc200-7bfd-11eb-8923-924e764cff37.png)

I just tried things here and it appears to be correct. Please let me know if this solves the problem or not.
Thanks.

**Comment by MrYsLab** [comment]
Ah- I think I understand what may have happened. I did not update setup.py on this repo, but only in my environment. I just fixed that and reissued version 0.4. If you downloaded the .zip and installed it with setup.py, please download again and reinstall. No special options are necessary instructions are necessary.

I also updated the readme file for the repo to give the upgrade option when using pip.

Sorry about the confusion.

**Comment by MrYsLab** [comment]
I think between the 2 solutions, this should be fixed. I am closing the issue, but if you are still having problems, I will re-open it. Thanks for the report.
